name: vercel-deploy-on-push-success

on:
  push:
    branches: [develop]

concurrency:
  group: vercel-deploy-develop
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4   # <-- KHÔNG truyền ref cho event push

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm i -g vercel@latest

      
