name: deploy-on-tag (FE)
on:
  push:
    tags:
      - 'v*.*.*'   # ví dụ: v1.1.0

concurrency:
  group: vercel-deploy-prod
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # nếu dùng OIDC tới cloud

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build (Vite)
        run: |
          npm ci
          npm run build

      #    - run: npm i -g vercel@latest

      #    # Lấy env từ Vercel (production)
      #    - run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }} ${{ secrets.VERCEL_PROJECT_ID && secrets.VERCEL_ORG_ID && format('--project {0} --scope {1}', secrets.VERCEL_PROJECT_ID, secrets.VERCEL_ORG_ID) || '' }}
      #     # Deploy production dùng artefact build sẵn
      #    - run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }} ${{ secrets.VERCEL_PROJECT_ID && secrets.VERCEL_ORG_ID && format('--project {0} --scope {1}', secrets.VERCEL_PROJECT_ID, secrets.VERCEL_ORG_ID) || '' }}


      # ========== CHỌN 1 TRONG CÁC CÁCH DEPLOY DƯỚI ĐÂY ==========

      # --- (A) Deploy FE static lên S3 + CloudFront ---
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-1
      #
      # - name: Sync to S3
      #   uses: aws-actions/s3-sync@v2
      #   with:
      #     source: dist
      #     destination: s3://YOUR_FE_BUCKET
      #
      # - name: Invalidate CloudFront
      #   uses: awact/cloudfront-action@v1.1.0
      #   with:
      #     distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation-path: "/*"
      #     aws-region: ap-southeast-1
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # --- (B) Deploy FE lên Vercel (Production) ---
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: .
      #     prod: true

      # --- (C) Deploy FE lên Netlify ---
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: ./dist
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
      #     production-deploy: true

      # --- (D) GitHub Pages (SPA) ---
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4

      # ========== KẾT THÚC LỰA CHỌN ==========
      - name: Done
        run: echo "Deployed FE tag ${{ github.ref_name }}"
